version: '3'

services:
    mysql-dev:
      image: mysql:8.0.2
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: app
      ports:
        - "10000:3306"
    client:
      image: mysql:8.0.2
      depends_on:
        - mysql-dev
      command: mysql -uroot -ppassword -hmysql-dev app
