version: '3.2'
services:
  registry:
    image: registry:2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '444:444'
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:444
      REGISTRY_STORAGE_MAINTENANCE: |-
          uploadpurging:
              enabled: false
          readonly:
              enabled: false
    volumes:
      - /var/lib/car-planner/registry:/var/lib/registry


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'car-planner'
      MYSQL_ROOT_PASSWORD: 'mypassword'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /var/lib/car-planner/mysql:/var/lib/mysql
      - /var/lib/car-planner/mysql-conf/mycustom.cnf:/etc/mysql/conf.d/mycustom.cnf
    networks:
      - webnet


  flask:
    image: flask-image
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - '443:5000'
    depends_on:
      - mysql
    volumes:
      - /home/ebi/Desktop/Git/licenta/Aplicatie/Flask:/app
    networks:
      - webnet


  emailer:
    image: emailer-image
    command: tail -f /dev/null
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
    volumes:
      - /home/ebi/Desktop/Git/licenta/Aplicatie/Flask:/app
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
    internal: false
